# Generated by Django 3.2.5 on 2021-07-24 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='href',
            field=models.TextField(blank=True, verbose_name='ссылка'),
        ),
    ]
