# Generated by Django 3.2.5 on 2021-08-19 16:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 21, 16, 7, 56, 282242, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='shopuser',
            name='activations_key',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
